"""In-memory per-session state for the estimator agent loop.

Two structures live here:

- ``ConversationHistory`` — a sliding-window chat log. When the window
  overflows, the oldest non-system messages are dropped; ``system`` messages
  are pinned (losing them would erase the role definition mid-conversation).
- ``ProjectMetadata`` — a Pydantic slot-filling target the agent updates as
  the user reveals project details (name, team size, technologies, scope).

Both are composed into a ``Session`` indexed by ``session_id`` in a
process-local dictionary.

Volatility trade-off (Step 1):
    The registry is a plain ``dict[str, Session]`` in the worker's memory.
    That means:
        * Restarting the API wipes every session.
        * Running multiple uvicorn workers gives each worker its own view —
          a client may hit a worker that has never seen its session.
        * No TTL, no eviction policy: memory grows for as long as the
          process lives.
    We accept this for now because:
        1. We are still validating the agent loop end-to-end; choosing a
           persistence layer (Redis schema, TTL, serialization) before the
           conversation contract has stabilised would bake in premature
           assumptions.
        2. The cost of a lost session at this stage is "the user starts
           over", not data loss — acceptable until there are real users.
    Next phase: hide this registry behind an interface and back it with
    Redis (the same instance already used by the cache layer).
"""

from __future__ import annotations

from typing import Literal

import structlog
from pydantic import BaseModel, Field

log = structlog.get_logger()


Role = Literal["system", "user", "assistant"]


class Message(BaseModel):
    """A single chat message in the canonical role/content shape used by
    every LLM SDK we wrap (OpenAI, Anthropic, LiteLLM)."""

    role: Role
    content: str


DEFAULT_MAX_TURNS = 6


class ConversationHistory:
    """Sliding-window chat log of (user, assistant) pairs.

    Design choices:
        - The system prompt is *not* stored here. It is regenerated by
          ``to_messages_list`` on every call from the current
          ``ProjectMetadata`` so the rendered facts stay in sync with what
          the extractor produced after the previous turn.
        - ``max_turns`` bounds the number of completed user/assistant
          *pairs* (default 6 = 12 stored messages). When the limit is
          exceeded, the oldest pair is dropped — never half a pair, since
          an orphaned user message without its assistant reply would skew
          the model's interpretation of the conversation.
        - Trimming happens on every ``add`` to keep the in-memory footprint
          predictable, which matters while the registry has no eviction.
    """

    def __init__(self, max_turns: int = DEFAULT_MAX_TURNS) -> None:
        self.max_turns = max_turns
        self._messages: list[Message] = []

    def add(self, role: Role, content: str) -> None:
        # System messages are regenerated by ``to_messages_list`` from the
        # current ProjectMetadata on every turn — there's no value in
        # persisting one here. We silently drop them so legacy callers that
        # pre-date Step 5 keep working without raising.
        if role == "system":
            log.debug("conversation_history_skip_system_add")
            return
        self._messages.append(Message(role=role, content=content))
        self._trim()

    def _trim(self) -> None:
        """Drop oldest complete pairs while the window is full.

        A "pair" is two adjacent messages starting with role ``user``.
        We compute the number of complete pairs from the head and drop
        them two at a time. A trailing unpaired user message (the current
        turn before the assistant responds) is preserved.
        """
        max_messages = self.max_turns * 2
        if len(self._messages) <= max_messages:
            return
        # Drop in pairs from the head. Walk forward keeping role alternation
        # (user, assistant) intact; if the head isn't a user message — which
        # would mean a corrupted history — drop one message to recover.
        excess = len(self._messages) - max_messages
        drop = excess + (excess % 2)  # round up to an even number
        # Try to keep alignment: ensure the first kept message is a user.
        kept = self._messages[drop:]
        if kept and kept[0].role != "user":
            kept = kept[1:]
        self._messages = kept

    @property
    def messages(self) -> list[Message]:
        return list(self._messages)

    @property
    def completed_turns(self) -> int:
        """Number of fully closed (user, assistant) pairs in the window."""
        pairs = 0
        i = 0
        while i + 1 < len(self._messages):
            if (
                self._messages[i].role == "user"
                and self._messages[i + 1].role == "assistant"
            ):
                pairs += 1
                i += 2
            else:
                i += 1
        return pairs

    def to_messages_list(self, system_prompt: str) -> list[dict[str, str]]:
        """Return the LLM-ready message array.

        The system prompt is prepended fresh on every call — callers render
        it from the current ``ProjectMetadata`` (and other context) so the
        prompt always reflects the latest known facts. The rest of the
        array is the trimmed user/assistant log in insertion order.
        """
        return [
            {"role": "system", "content": system_prompt},
            *({"role": m.role, "content": m.content} for m in self._messages),
        ]

    def __len__(self) -> int:
        return len(self._messages)


class ProjectMetadata(BaseModel):
    """Distilled facts about the project under estimation.

    Survives history truncation. Updated after each turn by the metadata
    extractor and injected into the next turn's system prompt — so a fact
    established four turns ago is still authoritative even after that turn
    has rolled out of the sliding window.

    Fields are optional because chats start empty and fill in across
    multiple turns. ``mentioned_technologies``, ``explicit_constraints``
    and ``rejected_options`` are cumulative lists; once a value lands
    there it should remain until the user revises it.
    """

    project_name: str | None = Field(default=None, max_length=120)
    assumed_team_size: int | None = Field(default=None, ge=1, le=50)
    mentioned_technologies: list[str] = Field(default_factory=list)
    agreed_scope: str | None = Field(default=None, max_length=4000)
    explicit_constraints: list[str] = Field(default_factory=list)
    rejected_options: list[str] = Field(default_factory=list)


class Session:
    """Per-session state: conversation history + project metadata.

    Plain class (not a Pydantic model) so ``ConversationHistory`` can stay
    a mutable container without ``arbitrary_types_allowed`` gymnastics.
    """

    def __init__(self, session_id: str, max_turns: int = DEFAULT_MAX_TURNS) -> None:
        self.session_id = session_id
        self.history = ConversationHistory(max_turns=max_turns)
        self.metadata = ProjectMetadata()


# ---------------------------------------------------------------------------
# Process-local registry
# ---------------------------------------------------------------------------

_SESSIONS: dict[str, Session] = {}


def get_or_create_session(
    session_id: str, *, max_turns: int = DEFAULT_MAX_TURNS
) -> Session:
    session = _SESSIONS.get(session_id)
    if session is None:
        session = Session(session_id=session_id, max_turns=max_turns)
        _SESSIONS[session_id] = session
        log.info("session_created", session_id=session_id, max_turns=max_turns)
    return session


def get_session(session_id: str) -> Session | None:
    """Read-only accessor: returns the existing session or ``None``."""
    return _SESSIONS.get(session_id)


def drop_session(session_id: str) -> bool:
    return _SESSIONS.pop(session_id, None) is not None


def active_session_ids() -> list[str]:
    """Useful for /debug endpoints and tests; not for production traffic."""
    return list(_SESSIONS.keys())
